# Generated by Django 6.0.1 on 2026-01-30 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('circulos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jovem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('contato', models.CharField(max_length=100)),
                ('ativo', models.BooleanField(default=True)),
                ('circulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='circulos.circulo')),
            ],
        ),
    ]
