# Generated by Django 5.2.8 on 2026-01-31 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circulos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='circulo',
            name='cor',
            field=models.CharField(default='Branco', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='circulo',
            name='nome',
            field=models.CharField(max_length=20),
        ),
    ]
