# Generated by Django 6.0.1 on 2026-01-30 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('circulos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reuniao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('GERAL', 'Geral'), ('CIRCULO', 'Círculo')], max_length=10)),
                ('data', models.DateField()),
                ('circulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='circulos.circulo')),
            ],
        ),
    ]
