# Generated by Django 5.2.8 on 2026-01-31 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reunioes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reuniao',
            name='tipo',
        ),
        migrations.AddField(
            model_name='reuniao',
            name='titulo',
            field=models.CharField(default='Branc', max_length=100),
            preserve_default=False,
        ),
    ]
