# Generated by Django 6.0.1 on 2026-01-30 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jovens', '0001_initial'),
        ('reunioes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presente', models.BooleanField(default=False)),
                ('jovem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jovens.jovem')),
                ('reuniao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reunioes.reuniao')),
            ],
        ),
    ]
