# Generated by Django 5.2.8 on 2026-01-31 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presencas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presenca',
            name='presente',
            field=models.BooleanField(default=True),
        ),
    ]
